name: Auto-Generate Sitemap

on:
  push:
    branches: [ main ]
    paths: 
      - '**.html'
      - '!sitemap.xml'

permissions:
  contents: write

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Generate Sitemap
      run: node generate-sitemap.js
    
    - name: Commit Sitemap
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git diff --staged --quiet || git commit -m "Auto-update sitemap.xml"
        git push 